package com.jive.myco.jazz.api.core.network;

import java.net.InetAddress;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NonNull;

/**
 * Represents the binding of a resource, service, etc. to a particular connector that exposes the
 * resource. At its most primitive level, a connector binding represents the host and port on which
 * some resource may be accessed.
 *
 * @author David Valeri
 */
@Builder
@AllArgsConstructor
@Getter
public class ConnectorBinding
{
  /**
   * Represents the connector name generated by the underlying server.
   */
  @NonNull
  private final String connectorName;

  /**
   * The network ID for the network on which this connector is bound.
   */
  @NonNull
  private final NetworkId networkId;

  /**
   * The actual IP address on which this connector is bound.
   */
  @NonNull
  private final InetAddress inetAddress;

  /**
   * The actual port on which this connector is bound.
   */
  private final int port;
}
